version: '2'
services:
  nginx:
    container_name: ${SERVER_NAME}.nginx
    build: nginx
    volumes:
      - ./nginx/access.log:/var/log/nginx/${SERVER_NAME}.default.log
      - ./nginx/error.log:/var/log/nginx/${SERVER_NAME}.error.log
      - /etc/hosts:/etc/hosts
      - ./nginx/default.crt:/srv/config/fullchain.pem
      - ./nginx/default.key:/srv/config/privkey.pem
    environment:
      HTTPS_ONLY: 'true'
      NGINX_ROOT: ${NGINX_ROOT}
    volumes_from: 
      - php
    privileged: true
    restart: ${RESTART}
    ports:
      - 80:80
      - 443:443 
  php:
    build: php
    container_name: ${SERVER_NAME}.php
    volumes:
      - /php
      - ../:${WORKING_DIR}
      - ./php/php.log:/var/log/php.log
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/locale:/etc/default/locale
      - ../mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    volumes_from: 
      - mysql
    working_dir: ${WORKING_DIR}
    links:
      - mysql
    privileged: true
    restart: ${RESTART}
  mysql:
    container_name: ${SERVER_NAME}.mysql
    build: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVER_NAME: ${SERVER_NAME}
    expose: 
      - '3306'
    volumes:
      - /run/mysqld
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ../mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: ${RESTART}
    # ports:
    #   - '3306:3306'
